# Form implementation generated from reading ui file 'c:\Users\Usuario\Desktop\Proyecto-Final-Practicas-2\usuario.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 300)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.boton_ver_productos = QtWidgets.QPushButton(parent=self.centralwidget)
        self.boton_ver_productos.setObjectName("boton_ver_productos")
        self.verticalLayout.addWidget(self.boton_ver_productos)
        self.boton_estadisticas = QtWidgets.QPushButton(parent=self.centralwidget)
        self.boton_estadisticas.setObjectName("boton_estadisticas")
        self.verticalLayout.addWidget(self.boton_estadisticas)
        self.boton_historial_precios = QtWidgets.QPushButton(parent=self.centralwidget)
        self.boton_historial_precios.setObjectName("boton_historial_precios")
        self.verticalLayout.addWidget(self.boton_historial_precios)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Pantalla Principal - Usuario"))
        self.boton_ver_productos.setText(_translate("MainWindow", "Ver Productos"))
        self.boton_estadisticas.setText(_translate("MainWindow", "Estadísticas"))
        self.boton_historial_precios.setText(_translate("MainWindow", "Historial de Precios"))
